import { useState, useEffect, useCallback } from 'react';
import { SupportedLanguage, LanguageOption } from '../types';

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English', greeting: 'Welcome to Praan Telehealth' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी', greeting: 'प्राण टेलिहेल्थ नेटवर्कमध्ये आपले स्वागत आहे' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', greeting: 'प्राण टेलीहेल्थ नेटवर्क में आपका स्वागत है' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', greeting: 'பிராண் டெலிஹெல்த் நெட்வொர்க்கிற்கு வருக' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', greeting: 'ప్రాణ్ టెలిహెల్త్ నెట్‌వర్క్‌కు స్వాగతం' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', greeting: 'প্রাণ টেলিহেলথ নেটওয়ার্কে স্বাগতম' }
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    appName: 'Praan Health Grid',
    appSubtitle: 'Federated Rural Telemedicine & Interoperable Public Healthcare Grid',
    loginPortalTitle: 'National Health Grid Access Portal',
    loginPortalSubtitle: 'Select your registered health facility or enter administrative credentials to access the federated network',
    quickDemoAccess: '1-Click Fast-Logins (5 Tiered Facilities):',
    loginButton: 'Secure Facility Sign In',
    emailPlaceholder: 'facility_id@telemed.gov.in',
    passwordPlaceholder: 'Enter security passkey',
    activeHospital: 'Active Facility',
    tierHwc: 'Sub-Centre / Ayushman Arogya Mandir',
    tierPhc: 'Primary Health Centre (PHC)',
    tierChc: 'Community Health Centre (CHC)',
    tierDh: 'District Civil Hospital (DH)',
    tierApex: 'Apex Medical College & Tele-ICU Hub',
    tierHwcShort: 'Sub-Centre (HWC)',
    tierPhcShort: 'Primary (PHC)',
    tierChcShort: 'Community (CHC)',
    tierDhShort: 'District (DH)',
    tierApexShort: 'Apex College',
    tier1SubCentre: 'Tier 1 · Sub-Centre',
    tier2PrimaryCare: 'Tier 2 · Primary Care',
    tier3Community: 'Tier 3 · Community',
    tier4DistrictHospital: 'Tier 4 · District Hospital',
    tier5ApexMedicalCollege: 'Tier 5 · Apex Medical College',
    gridTag: 'Public Telemedicine Grid',
    awsFirebaseStatus: 'AWS Cloud & Firebase Firestore',
    resetDemoBtn: 'Reset',
    recordsResetSuccess: 'Hospital records reset successfully on Cloud storage.',
    heroBannerTag: 'Public Healthcare Telemedicine Grid',
    careThatReaches: 'Care that reaches',
    everyDoorstep: 'every doorstep.',
    heroDescription: 'Federated digital health grid connecting frontline Sub-Centres with Specialist CHCs, District Hospitals, and Apex Medical Colleges.',
    fiveTierNetwork: '5-Tier Public Network',
    allFacilities: 'All Facilities',
    searchFacilityPlaceholder: 'Search facility name or block...',
    bedsFree: 'beds free',
    block: 'Block',
    node: 'Node',
    teleStations: 'Tele-Stations',
    enterHospital: 'Enter Hospital',
    selectedHospitalWorkspace: 'Selected Hospital Workspace',
    enteringPortal: 'Entering Portal...',
    saveAsHtml: 'Save as HTML',
    switchHospital: 'Switch Hospital',
    online: 'Online',
    offline: 'Offline',
    doctorRoster: 'Doctor Roster',
    navQueue: 'Live Teleconsult Queue',
    navConsultation: 'Assisted Tele-OPD',
    navTriage: 'Digital Triage & CDSS',
    navRecords: 'Hospital Patient Database',
    navReferrals: 'Inter-Hospital Referrals',
    navPharmacy: 'Medicine & Lab Grid',
    navHighRisk: 'High-Risk Follow-Up',
    navDoctors: 'Doctors & Hospital Roster',
    navAnalytics: 'Public Health Analytics',
    logout: 'Switch Facility',
    offlineMode: 'Offline Low-Bandwidth Mode',
    offlineSyncPending: 'items pending sync',
    syncNow: 'Sync to Grid',
    newConsultation: 'Start Assisted Consultation',
    triageScore: 'Triage Priority',
    emergencyRed: 'EMERGENCY (RED)',
    urgentYellow: 'URGENT (YELLOW)',
    routineGreen: 'ROUTINE (GREEN)',
    vitalsHud: 'Live Vitals & Diagnostic Telemetry',
    bloodPressure: 'Blood Pressure',
    pulseRate: 'Heart Rate',
    spO2: 'SpO2 Oxygen',
    tempF: 'Temperature',
    respRate: 'Resp. Rate',
    bloodSugar: 'Blood Sugar (RBS)',
    aiClinicalAssistant: 'AI Clinical Decision Support (CDSS)',
    differentialDiagnosis: 'Differential Diagnosis',
    redFlagAlerts: 'Clinical Red Flags',
    recommendedProtocol: 'Guideline Protocol Action',
    generatePrescription: 'Generate ABDM e-Prescription',
    prescribeMedication: 'Add Medicine',
    dosageInstructions: 'Dosage & Frequency',
    dietaryPrecautions: 'Dietary & Lifestyle Advice',
    dispatchAmbulance: 'Dispatch 108 Emergency Ambulance',
    referPatient: 'Transfer to Higher Facility',
    federatedStockSearch: 'Federated 5-Hospital Medicine Stock Explorer',
    stockAvailable: 'In Stock',
    stockLow: 'Low Stock',
    stockCritical: 'Stockout',
    requestStockTransfer: 'Request Inter-Hospital Stock Requisition',
    abhaId: 'ABHA Health ID',
    ashaAssisted: 'ASHA / ANM Assisted Mode',
    speechTranslate: 'Audio Translation & Voice Advice',
    speakOutLoud: 'Listen in Patient Language',
    languageSelect: 'Language / भाषा'
  },
  mr: {
    appName: 'प्राण हेल्थ ग्रीड',
    appSubtitle: 'एकात्मिक ग्रामीण टेलिमेडिसीन व सार्वजनिक आरोग्य नेटवर्क',
    loginPortalTitle: 'सार्वजनिक आरोग्य सेवा प्रवेश पोर्टल',
    loginPortalSubtitle: 'आपल्या नोंदणीकृत आरोग्य केंद्राची निवड करा अथवा थेट लॉगिन करा',
    quickDemoAccess: '५ रुग्णालयांचे थेट जलद लॉगिन:',
    loginButton: 'सुरक्षित आरोग्य केंद्र लॉगिन',
    emailPlaceholder: 'hwc_shirur@telemed.gov.in',
    passwordPlaceholder: 'पासवर्ड प्रविष्ट करा',
    activeHospital: 'सक्रिय आरोग्य केंद्र',
    tierHwc: 'आरोग्यवर्धिनी उपकेंद्र (HWC)',
    tierPhc: 'प्राथमिक आरोग्य केंद्र (PHC)',
    tierChc: 'ग्रामीण रुग्णालय / सीएचसी (CHC)',
    tierDh: 'जिल्हा सामान्य रुग्णालय (DH)',
    tierApex: 'ससून सर्वोपचार वैद्यकीय महाविद्यालय (Apex)',
    tierHwcShort: 'उपकेंद्र (HWC)',
    tierPhcShort: 'प्राथमिक केंद्र (PHC)',
    tierChcShort: 'ग्रामीण रुग्णालय (CHC)',
    tierDhShort: 'जिल्हा रुग्णालय (DH)',
    tierApexShort: 'अपेक्स कॉलेज',
    tier1SubCentre: 'स्तर १ · उपकेंद्र',
    tier2PrimaryCare: 'स्तर २ · प्राथमिक केंद्र',
    tier3Community: 'स्तर ३ · ग्रामीण रुग्णालय',
    tier4DistrictHospital: 'स्तर ४ · जिल्हा रुग्णालय',
    tier5ApexMedicalCollege: 'स्तर ५ · अपेक्स वैद्यकीय महाविद्यालय',
    gridTag: 'सार्वजनिक टेलिमेडिसिन ग्रिड',
    awsFirebaseStatus: 'AWS क्लाउड व फायरबेस डेटाबेस',
    resetDemoBtn: 'रीसेट',
    recordsResetSuccess: 'रुग्णालयातील नोंदी क्लाउड स्टोरेजवर पूर्ववत रीसेट झाल्या.',
    heroBannerTag: 'सार्वजनिक आरोग्य टेलिमेडिसिन ग्रिड',
    careThatReaches: 'प्रत्येक घरापर्यंत पोहोचणारी',
    everyDoorstep: 'आरोग्यसेवा.',
    heroDescription: 'उपकेंद्रांना तज्ज्ञ सीएचसी, जिल्हा रुग्णालय व ससून मेडिकल कॉलेजशी जोडणारे डिजिटल आरोग्य नेटवर्क.',
    fiveTierNetwork: '५-स्तरीय सार्वजनिक नेटवर्क',
    allFacilities: 'सर्व आरोग्य केंद्रे',
    searchFacilityPlaceholder: 'आरोग्य केंद्र किंवा तालुक्याचे नाव शोधा...',
    bedsFree: 'खाटा शिल्लक',
    block: 'तालुका',
    node: 'नोड',
    teleStations: 'टेलि-स्टेशन्स',
    enterHospital: 'आरोग्य केंद्रात प्रवेश करा',
    selectedHospitalWorkspace: 'निवडलेले रुग्णालय कार्यक्षेत्र',
    enteringPortal: 'प्रवेश करत आहे...',
    saveAsHtml: 'HTML डाउनलोड',
    switchHospital: 'रुग्णालय बदला',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    doctorRoster: 'डॉक्टर रोस्टर',
    navQueue: 'थेट टेलिकन्सल्टेशन रांग',
    navConsultation: 'सहाय्यक टेलि-ओपीडी',
    navTriage: 'डिजिटल ट्रायज व एआय सल्ला',
    navRecords: 'रुग्णालय रुग्ण डेटाबेस (Patient Database)',
    navReferrals: 'रुग्णालय रेफरल ट्रॅकिंग',
    navPharmacy: 'औषध व लॅब साठा ग्रिड',
    navHighRisk: 'अतिजोखमीचे रुग्ण पाठपुरावा',
    navDoctors: 'डॉक्टर रोस्टर व उपलब्धता',
    navAnalytics: 'आरोग्य विश्लेषण डॅशबोर्ड',
    logout: 'रुग्णालय बदला',
    offlineMode: 'कमी इंटरनेट (ऑफलाइन) मोड',
    offlineSyncPending: 'नोंदी सिंक बाकी',
    syncNow: 'आता सिंक करा',
    newConsultation: 'नवीन सल्लामसलत सुरू करा',
    triageScore: 'प्राधान्य वर्गवारी',
    emergencyRed: 'अतितातडीचे (लाल)',
    urgentYellow: 'तातडीचे (पिवळा)',
    routineGreen: 'सर्वसाधारण (हिरवा)',
    vitalsHud: 'थेट शरीराची लक्षणे व तपासणी',
    bloodPressure: 'रक्तदाब (BP)',
    pulseRate: 'नाडीचे ठोके',
    spO2: 'ऑक्सिजन प्रमाण (SpO2)',
    tempF: 'शरीराचे तापमान',
    respRate: 'श्वसन दर',
    bloodSugar: 'रक्तातील साखर (RBS)',
    aiClinicalAssistant: 'एआय वैद्यकीय सल्लागार प्रणाली',
    differentialDiagnosis: 'संभाव्य निदान',
    redFlagAlerts: 'धोक्याचे इशारे (Red Flags)',
    recommendedProtocol: 'तातडीने करावयाची कृती',
    generatePrescription: 'डिजिटल ई-प्रिस्क्रिप्शन तयार करा',
    prescribeMedication: 'औषध जोडा',
    dosageInstructions: 'औषध घेण्याची वेळ व पद्धत',
    dietaryPrecautions: 'आहार व काळजी',
    dispatchAmbulance: '१०८ रुग्णवाहिका बोलवा',
    referPatient: 'वरिष्ठ रुग्णालयात वर्ग करा',
    federatedStockSearch: '५ रुग्णालयांमधील थेट औषध साठा शोध',
    stockAvailable: 'साठा उपलब्ध',
    stockLow: 'कमी साठा',
    stockCritical: 'साठा संपला',
    requestStockTransfer: 'दुसऱ्या रुग्णालयातून औषध मागणी करा',
    abhaId: 'आभा आरोग्य क्रमांक',
    ashaAssisted: 'आशा / एएनएम सहाय्यक पद्धत',
    speechTranslate: 'स्थानिक भाषेत आवाज ऐका',
    speakOutLoud: 'रुग्णाच्या भाषेत सूचना ऐकवा',
    languageSelect: 'भाषा / Language'
  },
  hi: {
    appName: 'प्राण हेल्थ ग्रिड',
    appSubtitle: 'एकीकृत ग्रामीण टेलीमेडिसिन एवं सार्वजनिक स्वास्थ्य नेटवर्क',
    loginPortalTitle: 'सार्वजनिक स्वास्थ्य सेवा प्रवेश पोर्टल',
    loginPortalSubtitle: 'अपने पंजीकृत स्वास्थ्य केंद्र का चयन करें या लॉगिन क्रेडेंशियल दर्ज करें',
    quickDemoAccess: '5 अस्पतालों का त्वरित लॉगिन:',
    loginButton: 'सुरक्षित अस्पताल लॉगिन',
    emailPlaceholder: 'facility_id@telemed.gov.in',
    passwordPlaceholder: 'पासवर्ड दर्ज करें',
    activeHospital: 'सक्रिय स्वास्थ्य केंद्र',
    tierHwc: 'आयुष्मान आरोग्य मंदिर (HWC)',
    tierPhc: 'प्राथमिक स्वास्थ्य केंद्र (PHC)',
    tierChc: 'सामुदायिक स्वास्थ्य केंद्र (CHC)',
    tierDh: 'जिला सिविल अस्पताल (DH)',
    tierApex: 'शीर्ष मेडिकल कॉलेज व टेली-आईसीयू',
    tierHwcShort: 'उपकेंद्र (HWC)',
    tierPhcShort: 'प्राथमिक केंद्र (PHC)',
    tierChcShort: 'सामुदायिक केंद्र (CHC)',
    tierDhShort: 'जिला अस्पताल (DH)',
    tierApexShort: 'शीर्ष मेडिकल कॉलेज',
    tier1SubCentre: 'स्तर 1 · उप-स्वास्थ्य केंद्र',
    tier2PrimaryCare: 'स्तर 2 · प्राथमिक स्वास्थ्य केंद्र',
    tier3Community: 'स्तर 3 · सामुदायिक स्वास्थ्य केंद्र',
    tier4DistrictHospital: 'स्तर 4 · जिला सिविल अस्पताल',
    tier5ApexMedicalCollege: 'स्तर 5 · शीर्ष मेडिकल कॉलेज',
    gridTag: 'सार्वजनिक टेलीमेडिसिन ग्रिड',
    awsFirebaseStatus: 'AWS क्लाउड एवं फायरबेस डेटाबेस',
    resetDemoBtn: 'रीसेट',
    recordsResetSuccess: 'अस्पताल रिकॉर्ड्स क्लाउड स्टोरेज पर सफलतापूर्वक रीसेट किए गए।',
    heroBannerTag: 'सार्वजनिक स्वास्थ्य टेलीमेडिसिन ग्रिड',
    careThatReaches: 'हर घर तक पहुँचने वाली',
    everyDoorstep: 'स्वास्थ्य सेवा।',
    heroDescription: 'उपकेंद्रों को विशेषज्ञ सीएचसी, जिला अस्पतालों और शीर्ष मेडिकल कॉलेजों से जोड़ने वाला डिजिटल स्वास्थ्य नेटवर्क।',
    fiveTierNetwork: '5-स्तरीय सार्वजनिक नेटवर्क',
    allFacilities: 'सभी स्वास्थ्य केंद्र',
    searchFacilityPlaceholder: 'स्वास्थ्य केंद्र या ब्लॉक का नाम खोजें...',
    bedsFree: 'बेड खाली',
    block: 'ब्लॉक',
    node: 'नोड',
    teleStations: 'टेली-स्टेशन',
    enterHospital: 'अस्पताल में प्रवेश करें',
    selectedHospitalWorkspace: 'चयनित अस्पताल कार्यक्षेत्र',
    enteringPortal: 'प्रवेश हो रहा है...',
    saveAsHtml: 'HTML सेव करें',
    switchHospital: 'अस्पताल बदलें',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    doctorRoster: 'डॉक्टर रोस्टर',
    navQueue: 'लाइव टेलीपरामर्श कतार',
    navConsultation: 'सहायक टेली-ओपीडी',
    navTriage: 'डिजिटल ट्राइएज व एआई सहायता',
    navRecords: 'अस्पताल मरीज़ डेटाबेस (Patient Database)',
    navReferrals: 'अंतर-अस्पताल रेफरल ट्रैकिंग',
    navPharmacy: 'दवा व लैब उपलब्धता ग्रिड',
    navHighRisk: 'उच्च-जोखिम मरीज फॉलो-अप',
    navDoctors: 'डॉक्टर रोस्टर व उपलब्धता',
    navAnalytics: 'लोक स्वास्थ्य निगरानी',
    logout: 'अस्पताल बदलें',
    offlineMode: 'कम कनेक्टिविटी ऑफलाइन मोड',
    offlineSyncPending: 'सिंक लंबित',
    syncNow: 'सिंक करें',
    newConsultation: 'नया परामर्श प्रारंभ करें',
    triageScore: 'ट्राइएज प्राथमिकता',
    emergencyRed: 'अति-आपातकालीन (लाल)',
    urgentYellow: 'गंभीर (पीला)',
    routineGreen: 'सामान्य (हरा)',
    vitalsHud: 'लाइव वाइटल्स एवं जांच आंकड़े',
    bloodPressure: 'रक्तचाप (BP)',
    pulseRate: 'हृदय गति',
    spO2: 'ऑक्सीजन स्तर (SpO2)',
    tempF: 'शरीर का तापमान',
    respRate: 'श्वसन दर',
    bloodSugar: 'ब्लड शुगर (RBS)',
    aiClinicalAssistant: 'एआई नैदानिक निर्णय प्रणाली (CDSS)',
    differentialDiagnosis: 'संभावित रोग निदान',
    redFlagAlerts: 'गंभीर खतरे के लक्षण',
    recommendedProtocol: 'सुझाया गया प्राथमिक उपचार',
    generatePrescription: 'डिजिटल ई-पर्चे तैयार करें',
    prescribeMedication: 'दवा जोड़ें',
    dosageInstructions: 'खुराक एवं सेवन विधि',
    dietaryPrecautions: 'परहेज एवं आहार सलाह',
    dispatchAmbulance: '108 आपातकालीन एम्बुलेंस भेजें',
    referPatient: 'उच्च अस्पताल में रेफर करें',
    federatedStockSearch: '5 अस्पतालों में लाइव दवा स्टॉक खोज',
    stockAvailable: 'उपलब्ध',
    stockLow: 'कम स्टॉक',
    stockCritical: 'स्टॉक समाप्त',
    requestStockTransfer: 'दूसरे अस्पताल से दवा हस्तांतरण अनुरोध',
    abhaId: 'आभा हेल्थ आईडी',
    ashaAssisted: 'आशा / एएनएम सहायक मोड',
    speechTranslate: 'मरीज की भाषा में बोलकर समझाएं',
    speakOutLoud: 'ऑडियो सलाह सुनें',
    languageSelect: 'भाषा / Language'
  },
  ta: {
    appName: 'பிராண் ஹெல்த் கிரிட்',
    appSubtitle: 'ஒருங்கிணைந்த கிராமப்புற தொலைமருத்துவ வலையமைப்பு',
    loginPortalTitle: 'பொது சுகாதார நுழைவு போர்டல்',
    loginPortalSubtitle: 'உங்கள் மருத்துவமனையைத் தேர்ந்தெடுக்கவும் அல்லது உள்நுழையவும்',
    quickDemoAccess: '5 மருத்துவமனை நேரடி உள்நுழைவு:',
    loginButton: 'பாதுகாப்பான உள்நுழைவு',
    emailPlaceholder: 'facility@telemed.gov.in',
    passwordPlaceholder: 'கடவுச்சொல்',
    activeHospital: 'செயலில் உள்ள மருத்துவமனை',
    tierHwc: 'துணை நல்வாழ்வு மையம் (HWC)',
    tierPhc: 'ஆரம்ப சுகாதார நிலையம் (PHC)',
    tierChc: 'சமூக சுகாதார நிலையம் (CHC)',
    tierDh: 'மாவட்ட தலைமை மருத்துவமனை (DH)',
    tierApex: 'சிறப்பு மருத்துவக் கல்லூரி (Apex)',
    tierHwcShort: 'துணை மையம் (HWC)',
    tierPhcShort: 'ஆரம்ப மையம் (PHC)',
    tierChcShort: 'சமூக மையம் (CHC)',
    tierDhShort: 'மாவட்ட மருத்துவமனை (DH)',
    tierApexShort: 'அபெக்ஸ் கல்லூரி',
    tier1SubCentre: 'நிலை 1 · துணை மையம்',
    tier2PrimaryCare: 'நிலை 2 · ஆரம்ப சுகாதாரம்',
    tier3Community: 'நிலை 3 · சமூக மையம்',
    tier4DistrictHospital: 'நிலை 4 · மாவட்ட தலைமை மருத்துவமனை',
    tier5ApexMedicalCollege: 'நிலை 5 · சிறப்பு மருத்துவக் கல்லூரி',
    gridTag: 'பொது தொலைமருத்துவ கிரிட்',
    awsFirebaseStatus: 'AWS கிளவுட் & ஃபயர்பேஸ்',
    resetDemoBtn: 'மீட்டமை',
    recordsResetSuccess: 'மருத்துவமனை பதிவுகள் வெற்றிகரமாக மீட்டமைக்கப்பட்டன.',
    heroBannerTag: 'பொது சுகாதார தொலைமருத்துவ கிரிட்',
    careThatReaches: 'ஒவ்வொரு வாசலையும்',
    everyDoorstep: 'அடையும் சிகிச்சை.',
    heroDescription: 'துணை மையங்களை சிறப்பு சிஎச்சி, மாவட்ட மருத்துவமனைகள் மற்றும் மருத்துவக் கல்லூரிகளுடன் இணைக்கும் சுகாதார கிரிட்.',
    fiveTierNetwork: '5-நிலை பொது நெட்வொர்க்',
    allFacilities: 'அனைத்து மருத்துவமனைகள்',
    searchFacilityPlaceholder: 'மருத்துவமனை அல்லது வட்டாரத்தின் பெயரைத் தேடுங்கள்...',
    bedsFree: 'படுக்கைகள் உள்ளன',
    block: 'வட்டாரம்',
    node: 'நோட்',
    teleStations: 'டெலி-நிலையங்கள்',
    enterHospital: 'மருத்துவமனைக்குள் நுழைக',
    selectedHospitalWorkspace: 'தேர்ந்தெடுக்கப்பட்ட மருத்துவமனை பணியிடம்',
    enteringPortal: 'நுழைகிறது...',
    saveAsHtml: 'HTML சேமி',
    switchHospital: 'மருத்துவமனை மாற்று',
    online: 'ஆன்லைன்',
    offline: 'ஆஃப்லைன்',
    doctorRoster: 'மருத்துவர் அட்டவணை',
    navQueue: 'நேரலை ஆலோசனை வரிசை',
    navConsultation: 'உதவி டெலி-ஓபிடி',
    navTriage: 'டிஜிட்டல் ட்ரையேஜ் & AI',
    navRecords: 'நீண்டகால ABHA பதிவுகள்',
    navReferrals: 'பரிந்துரை கண்காணிப்பு',
    navPharmacy: 'மருந்து இருப்பு கிரிட்',
    navHighRisk: 'அதிக ஆபத்துள்ள பின்தொடர்தல்',
    navDoctors: 'மருத்துவர் அட்டவணை & இருப்பு',
    navAnalytics: 'பொது சுகாதார பகுப்பாய்வு',
    logout: 'மருத்துவமனை மாற்று',
    offlineMode: 'ஆஃப்லைன் முறை',
    offlineSyncPending: 'காத்திருக்கும் பதிவுகள்',
    syncNow: 'இணைக்க',
    newConsultation: 'ஆலோசனையைத் தொடங்கு',
    triageScore: 'முன்னுரிமை நிலை',
    emergencyRed: 'அவசரம் (சிவப்பு)',
    urgentYellow: 'முக்கியம் (மஞ்சள்)',
    routineGreen: 'சாதாரண (பச்சை)',
    vitalsHud: 'நேரலை உடல்நிலை அளவுருக்கள்',
    bloodPressure: 'இரத்த அழுத்தம்',
    pulseRate: 'நாடித் துடிப்பு',
    spO2: 'ஆக்சிஜன் அளவு',
    tempF: 'உடல் வெப்பநிலை',
    respRate: 'சுவாச விகிதம்',
    bloodSugar: 'இரத்த சர்க்கரை',
    aiClinicalAssistant: 'AI மருத்துவ வழிகாட்டி',
    differentialDiagnosis: 'சாத்தியமான நோயறிதல்',
    redFlagAlerts: 'எச்சரிக்கை அறிகுறிகள்',
    recommendedProtocol: 'பரிந்துரைக்கப்பட்ட சிகிச்சை',
    generatePrescription: 'இ-மருந்துச் சீட்டு',
    prescribeMedication: 'மருந்து சேர்க்க',
    dosageInstructions: 'அளவு மற்றும் நேரம்',
    dietaryPrecautions: 'உணவு முன்னெச்சரிக்கைகள்',
    dispatchAmbulance: '108 ஆம்புலன்ஸ் அனுப்பவும்',
    referPatient: 'மேல் மருத்துவமனைக்கு மாற்றவும்',
    federatedStockSearch: '5 மருத்துவமனை மருந்து இருப்பு தேடல்',
    stockAvailable: 'இருப்பு உள்ளது',
    stockLow: 'குறைந்த இருப்பு',
    stockCritical: 'இருப்பு இல்லை',
    requestStockTransfer: 'மருந்து கோரிக்கை அனுப்பவும்',
    abhaId: 'ABHA அடையாள அட்டை',
    ashaAssisted: 'ஆஷா பணியாளர் உதவி முறை',
    speechTranslate: 'குரல் வழிகாட்டுதல்',
    speakOutLoud: 'நோயாளியின் மொழியில் கேட்கவும்',
    languageSelect: 'மொழி / Language'
  },
  te: {
    appName: 'ప్రాణ్ హెల్త్ గ్రిడ్',
    appSubtitle: 'సమీకృత గ్రామీణ టెలిమెడిసిన్ & ప్రజారోగ్య నెట్‌వర్క్',
    loginPortalTitle: 'ప్రజారోగ్య సేవల పోర్టల్',
    loginPortalSubtitle: 'మీ ఆరోగ్య కేంద్రాన్ని ఎంచుకోండి లేదా లాగిన్ అవ్వండి',
    quickDemoAccess: '5 ఆసుపత్రుల శీఘ్ర లాగిన్:',
    loginButton: 'సురక్షిత లాగిన్',
    emailPlaceholder: 'facility@telemed.gov.in',
    passwordPlaceholder: 'పాస్వర్డ్',
    activeHospital: 'ప్రస్తుత ఆసుపత్రి',
    tierHwc: 'ఆరోగ్య ఉప కేంద్రం (HWC)',
    tierPhc: 'ప్రాథమిక ఆరోగ్య కేంద్రం (PHC)',
    tierChc: 'సామాజిక ఆరోగ్య కేంద్రం (CHC)',
    tierDh: 'జిల్లా ప్రభుత్వ ఆసుపత్రి (DH)',
    tierApex: 'సూపర్ స్పెషాలిటీ మెడికల్ కాలేజ్ (Apex)',
    tierHwcShort: 'ఉప కేంద్రం (HWC)',
    tierPhcShort: 'ప్రాథమిక కేంద్రం (PHC)',
    tierChcShort: 'సామాజిక కేంద్రం (CHC)',
    tierDhShort: 'జిల్లా ఆసుపత్రి (DH)',
    tierApexShort: 'అపెక్స్ కాలేజీ',
    tier1SubCentre: 'అంచె 1 · ఉప కేంద్రం',
    tier2PrimaryCare: 'అంచె 2 · ప్రాథమిక వైద్యం',
    tier3Community: 'అంచె 3 · సామాజిక ఆసుపత్రి',
    tier4DistrictHospital: 'అంచె 4 · జిల్లా ప్రభుత్వ ఆసుపత్రి',
    tier5ApexMedicalCollege: 'అంచె 5 · అపెక్స్ మెడికల్ కాలేజీ',
    gridTag: 'ప్రజారోగ్య టెలిమెడిసిన్ గ్రిడ్',
    awsFirebaseStatus: 'AWS క్లౌడ్ & ఫైర్‌బేస్',
    resetDemoBtn: 'రీసెట్',
    recordsResetSuccess: 'ఆసుపత్రి రికార్డులు క్లౌడ్ స్టోరేజ్‌లో విజయవంతంగా రీసెట్ చేయబడ్డాయి.',
    heroBannerTag: 'ప్రజారోగ్య టెలిమెడిసిన్ నెట్‌వర్క్',
    careThatReaches: 'ప్రతి ఇంటి గుమ్మానికి',
    everyDoorstep: 'చేరే వైద్య సేవలు.',
    heroDescription: 'ఉప కేంద్రాలను స్పెషలిస్ట్ సీహెచ్‌సీ, జిల్లా ఆసుపత్రులు మరియు మెడికల్ కాలేజీలతో అనుసంధానించే నెట్‌వర్క్.',
    fiveTierNetwork: '5-అంచెల ప్రజా నెట్‌వర్క్',
    allFacilities: 'అన్ని ఆరోగ్య కేంద్రాలు',
    searchFacilityPlaceholder: 'ఆసుపత్రి లేదా బ్లాక్ పేరు వెతకండి...',
    bedsFree: 'పడకలు ఖాళీగా ఉన్నాయి',
    block: 'బ్లాక్',
    node: 'నోడ్',
    teleStations: 'టెలి-స్టేషన్లు',
    enterHospital: 'ఆసుపత్రిలోకి ప్రవేశించండి',
    selectedHospitalWorkspace: 'ఎంచుకున్న ఆసుపత్రి వర్క్‌స్పేస్',
    enteringPortal: 'ప్రవేశిస్తోంది...',
    saveAsHtml: 'HTML సేవ్ చేయండి',
    switchHospital: 'ఆసుపత్రి మార్చండి',
    online: 'ఆన్‌లైన్',
    offline: 'ఆఫ్‌లైన్',
    doctorRoster: 'వైద్యుల జాబితా',
    navQueue: 'లైవ్ కన్సల్టేషన్ క్యూ',
    navConsultation: 'టెలి-ఓపీడీ సేవా విభాగం',
    navTriage: 'డిజిటల్ ట్రయాజ్ & AI',
    navRecords: 'దీర్ఘకాలిక ABHA రికార్డులు',
    navReferrals: 'రెఫరల్ ట్రాకింగ్',
    navPharmacy: 'మందులు & ల్యాబ్ గ్రిడ్',
    navHighRisk: 'హై-రిస్క్ రోగుల ఫాలో-అప్',
    navDoctors: 'వైద్యుల రోస్టర్ & లభ్యత',
    navAnalytics: 'ప్రజారోగ్య విశ్లేషణ',
    logout: 'ఆసుపత్రి మార్చండి',
    offlineMode: 'ఆఫ్‌లైన్ మోడ్',
    offlineSyncPending: 'సింక్ పెండింగ్',
    syncNow: 'సింక్ చేయండి',
    newConsultation: 'కొత్త కన్సల్టేషన్ ప్రారంభించండి',
    triageScore: 'ట్రయాజ్ ప్రాధాన్యత',
    emergencyRed: 'అత్యవసరం (ఎరుపు)',
    urgentYellow: 'ముఖ్యమైనది (పసుపు)',
    routineGreen: 'సాధారణం (ఆకుపచ్చ)',
    vitalsHud: 'వైటల్స్ & పరీక్షల రీడింగ్స్',
    bloodPressure: 'రక్తపోటు (BP)',
    pulseRate: 'గుండె చప్పుడు',
    spO2: 'ఆక్సిజన్ స్థాయి',
    tempF: 'శరీర ఉష్ణోగ్రత',
    respRate: 'శ్వాస వేగం',
    bloodSugar: 'షుగర్ లెవల్',
    aiClinicalAssistant: 'AI వైద్య నిర్ణయ సహాయక వ్యవస్థ',
    differentialDiagnosis: 'రోగ నిర్ధారణ',
    redFlagAlerts: 'ప్రమాద హెచ్చరికలు',
    recommendedProtocol: 'సూచించిన చికిత్స',
    generatePrescription: 'డిజిటల్ ప్రిస్క్రిప్షన్',
    prescribeMedication: 'మందు జోడించండి',
    dosageInstructions: 'మోతాదు మరియు వాడే విధానం',
    dietaryPrecautions: 'ఆహార జాగ్రత్తలు',
    dispatchAmbulance: '108 అంబులెన్స్ పంపండి',
    referPatient: 'పై ఆసుపత్రికి రిఫర్ చేయండి',
    federatedStockSearch: '5 ఆసుపత్రుల మందుల నిల్వల వివరాలు',
    stockAvailable: 'అందుబాటులో ఉంది',
    stockLow: 'తక్కువ నిల్వ',
    stockCritical: 'స్టాక్ లేదు',
    requestStockTransfer: 'మందుల బదిలీ అభ్యర్థన',
    abhaId: 'ABHA ఐడీ',
    ashaAssisted: 'ఆశా కార్యకర్త సహాయక మోడ్',
    speechTranslate: 'వాయిస్ అనువాదం',
    speakOutLoud: 'రోగి భాషలో వినండి',
    languageSelect: 'భాష / Language'
  },
  bn: {
    appName: 'প্রাণ হেলথ গ্রিড',
    appSubtitle: 'সমন্বিত গ্রামীণ টেলিমেডিসিন ও জনস্বাস্থ্য নেটওয়ার্ক',
    loginPortalTitle: 'জনস্বাস্থ্য পরিষেবা পোর্টাল',
    loginPortalSubtitle: 'আপনার স্বাস্থ্য কেন্দ্র নির্বাচন করুন বা লগইন করুন',
    quickDemoAccess: '৫টি হাসপাতালের দ্রুত লগইন:',
    loginButton: 'সুরক্ষিত লগইন',
    emailPlaceholder: 'facility@telemed.gov.in',
    passwordPlaceholder: 'পাসওয়ার্ড',
    activeHospital: 'বর্তমান স্বাস্থ্যকেন্দ্র',
    tierHwc: 'উপ-স্বাস্থ্য কেন্দ্র (HWC)',
    tierPhc: 'প্রাথমিক স্বাস্থ্য কেন্দ্র (PHC)',
    tierChc: 'গ্রামীণ হাসপাতাল / সিএইচসি (CHC)',
    tierDh: 'জেলা হাসপাতাল (DH)',
    tierApex: 'শীর্ষ মেডিক্যাল কলেজ (Apex)',
    tierHwcShort: 'উপ-কেন্দ্র (HWC)',
    tierPhcShort: 'প্রাথমিক কেন্দ্র (PHC)',
    tierChcShort: 'গ্রামীণ কেন্দ্র (CHC)',
    tierDhShort: 'জেলা হাসপাতাল (DH)',
    tierApexShort: 'অ্যাপেক্স কলেজ',
    tier1SubCentre: 'স্তর ১ · উপ-স্বাস্থ্য কেন্দ্র',
    tier2PrimaryCare: 'স্তর ২ · প্রাথমিক যত্ন',
    tier3Community: 'স্তর ৩ · গ্রামীণ হাসপাতাল',
    tier4DistrictHospital: 'স্তর ৪ · জেলা সদর হাসপাতাল',
    tier5ApexMedicalCollege: 'স্তর ৫ · শীর্ষ মেডিক্যাল কলেজ',
    gridTag: 'জনস্বাস্থ্য টেলিমেডিসিন গ্রিড',
    awsFirebaseStatus: 'AWS ক্লাউড ও ফায়ারবেস',
    resetDemoBtn: 'রিসেট',
    recordsResetSuccess: 'হাসপাতাল রেকর্ড ক্লাউড স্টোরেজে সফলভাবে রিসেট করা হয়েছে।',
    heroBannerTag: 'জনস্বাস্থ্য টেলিমেডিসিন গ্রিড',
    careThatReaches: 'প্রতিটি দোরগোড়ায় পৌঁছে যাওয়া',
    everyDoorstep: 'স্বাস্থ্যসেবা।',
    heroDescription: 'উপ-স্বাস্থ্য কেন্দ্রগুলিকে বিশেষজ্ঞ সিএইচসি, জেলা হাসপাতাল এবং মেডিকেল কলেজের সাথে যুক্তকারী ডিজিটাল স্বাস্থ্য গ্রিড।',
    fiveTierNetwork: '৫-স্তর বিশিষ্ট জনস্বাস্থ্য নেটওয়ার্ক',
    allFacilities: 'সমস্ত স্বাস্থ্য কেন্দ্র',
    searchFacilityPlaceholder: 'স্বাস্থ্যকেন্দ্র বা ব্লকের নাম খুঁজুন...',
    bedsFree: 'বেড খালি আছে',
    block: 'ব্লক',
    node: 'নোড',
    teleStations: 'টেলি-স্টেশন',
    enterHospital: 'হাসপাতালে প্রবেশ করুন',
    selectedHospitalWorkspace: 'নির্বাচিত হাসপাতাল ওয়ার্কস্পেস',
    enteringPortal: 'প্রবেশ করা হচ্ছে...',
    saveAsHtml: 'HTML সংরক্ষণ করুন',
    switchHospital: 'হাসপাতাল পরিবর্তন',
    online: 'অনলাইন',
    offline: 'অফলাইন',
    doctorRoster: 'ডাক্তার তালিকা',
    navQueue: 'লাইভ পরামর্শ কিউ',
    navConsultation: 'সহায়ক টেলি-ওপিডি',
    navTriage: 'ডিজিটাল ট্রায়াজ ও এআই',
    navRecords: 'দীর্ঘমেয়াদী আভা স্বাস্থ্য রেকর্ড',
    navReferrals: 'রেফারাল ট্র্যাকিং',
    navPharmacy: 'ওষুধ ও ল্যাব স্টক গ্রিড',
    navHighRisk: 'উচ্চ ঝুঁকিপূর্ণ রোগী ফলো-আপ',
    navDoctors: 'ডাক্তার রোস্টার ও উপস্থিতি',
    navAnalytics: 'জনস্বাস্থ্য নজরদারি',
    logout: 'হাসপাতাল পরিবর্তন',
    offlineMode: 'অফলাইন মোড',
    offlineSyncPending: 'সিঙ্ক বাকি',
    syncNow: 'সিঙ্ক করুন',
    newConsultation: 'নতুন পরামর্শ শুরু করুন',
    triageScore: 'ট্রায়াজ অগ্রাধিকার',
    emergencyRed: 'জরুরী (লাল)',
    urgentYellow: 'গুরুত্বপূর্ণ (হলুদ)',
    routineGreen: 'সাধারণ (সবুজ)',
    vitalsHud: 'শারীরিক লক্ষণ ও পরীক্ষা',
    bloodPressure: 'রক্তচাপ (BP)',
    pulseRate: 'নাড়ির গতি',
    spO2: 'অক্সিজেন মাত্রা',
    tempF: 'তাপমাত্রা',
    respRate: 'শ্বাসপ্রশ্বাসের হার',
    bloodSugar: 'ব্লাড সুগার',
    aiClinicalAssistant: 'এআই চিকিৎসা সহকারী (CDSS)',
    differentialDiagnosis: 'সম্ভাব্য রোগনির্ণয়',
    redFlagAlerts: 'বিপদের লক্ষণ',
    recommendedProtocol: 'জরুরী করণীয় পদক্ষেপ',
    generatePrescription: 'ই-প্রেসক্রিপশন তৈরি',
    prescribeMedication: 'ওষুধ যোগ করুন',
    dosageInstructions: 'ডোজ এবং নিয়মাবলী',
    dietaryPrecautions: 'খাদ্য ও সতর্কতা',
    dispatchAmbulance: '১০৮ অ্যাম্বুলেন্স প্রেরণ',
    referPatient: 'উচ্চ হাসপাতালে রেফার করুন',
    federatedStockSearch: '৫টি হাসপাতালের ওষুধ স্টক সন্ধান',
    stockAvailable: 'মজুদ আছে',
    stockLow: 'কম স্টক',
    stockCritical: 'স্টক শেষ',
    requestStockTransfer: 'অন্য হাসপাতাল থেকে ওষুধ আনুন',
    abhaId: 'আভা কার্ড আইডি',
    ashaAssisted: 'আশা কর্মী সহায়তা মোড',
    speechTranslate: 'ভয়েস অনুবাদ',
    speakOutLoud: 'রোগীর ভাষায় শুনুন',
    languageSelect: 'ভাষা / Language'
  }
};

export class LanguageService {
  private currentLanguage: SupportedLanguage = 'en';
  private listeners: Array<(lang: SupportedLanguage) => void> = [];

  constructor() {
    const saved = (typeof localStorage !== 'undefined'
      ? (localStorage.getItem('praan_language') || localStorage.getItem('sanjeevani_language'))
      : null) as SupportedLanguage;
    if (saved && TRANSLATIONS[saved]) {
      this.currentLanguage = saved;
    }
  }

  public getLanguage(): SupportedLanguage {
    return this.currentLanguage;
  }

  public setLanguage(lang: SupportedLanguage): void {
    if (TRANSLATIONS[lang]) {
      this.currentLanguage = lang;
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem('praan_language', lang);
        localStorage.setItem('sanjeevani_language', lang);
      }
      this.listeners.forEach((cb) => cb(lang));
    }
  }

  public t(key: string, fallback?: string): string {
    const dict = TRANSLATIONS[this.currentLanguage] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || fallback || key;
  }

  public subscribe(cb: (lang: SupportedLanguage) => void): () => void {
    this.listeners.push(cb);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== cb);
    };
  }

  public speak(text: string, langCode?: SupportedLanguage): void {
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      const target = langCode || this.currentLanguage;
      const langMap: Record<SupportedLanguage, string> = {
        en: 'en-IN',
        mr: 'mr-IN',
        hi: 'hi-IN',
        ta: 'ta-IN',
        te: 'te-IN',
        bn: 'bn-IN'
      };
      utterance.lang = langMap[target] || 'en-IN';
      utterance.rate = 0.95;
      window.speechSynthesis.speak(utterance);
    }
  }
}

export const languageService = new LanguageService();

export function useLanguage() {
  const [lang, setLang] = useState<SupportedLanguage>(languageService.getLanguage());

  useEffect(() => {
    const unsubscribe = languageService.subscribe((newLang) => {
      setLang(newLang);
    });
    return unsubscribe;
  }, []);

  const t = useCallback(
    (key: string, fallback?: string) => {
      return languageService.t(key, fallback);
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [lang]
  );

  const changeLanguage = useCallback((newLang: SupportedLanguage) => {
    languageService.setLanguage(newLang);
  }, []);

  return {
    language: lang,
    setLanguage: changeLanguage,
    t,
    speak: languageService.speak.bind(languageService)
  };
}
