import { pgTable, varchar, text, integer, numeric, jsonb, timestamp, boolean } from 'drizzle-orm/pg-core';

export const facilities = pgTable('facilities', {
  facilityId: varchar('facility_id', { length: 64 }).primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  shortName: varchar('short_name', { length: 64 }).notNull(),
  tier: varchar('tier', { length: 32 }).notNull(),
  tierLabel: varchar('tier_label', { length: 128 }).notNull(),
  blockName: varchar('block_name', { length: 128 }).notNull(),
  district: varchar('district', { length: 128 }).notNull(),
  state: varchar('state', { length: 128 }).notNull().default('Maharashtra'),
  pincode: varchar('pincode', { length: 10 }).notNull(),
  contactNumber: varchar('contact_number', { length: 32 }),
  email: varchar('email', { length: 255 }),
  latitude: numeric('latitude', { precision: 10, scale: 6 }),
  longitude: numeric('longitude', { precision: 10, scale: 6 }),
  totalBeds: integer('total_beds').default(0),
  occupiedBeds: integer('occupied_beds').default(0),
  icuBeds: integer('icu_beds').default(0),
  occupiedIcuBeds: integer('occupied_icu_beds').default(0),
  oxygenAvailableLiters: integer('oxygen_available_liters').default(0),
  doctorsOnDuty: integer('doctors_on_duty').default(1),
  teleconsultStations: integer('teleconsult_stations').default(1),
  activeSpecialities: jsonb('active_specialities').$type<string[]>().default([]),
  ambulancesStationed: integer('ambulances_stationed').default(0),
  staffName: varchar('staff_name', { length: 128 }),
  staffRole: varchar('staff_role', { length: 128 }),
  staffTitle: varchar('staff_title', { length: 128 }),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const patients = pgTable('patients', {
  id: varchar('id', { length: 64 }).primaryKey(),
  abhaId: varchar('abha_id', { length: 64 }).notNull(),
  name: varchar('name', { length: 255 }).notNull(),
  age: integer('age').notNull(),
  gender: varchar('gender', { length: 16 }).notNull(),
  phone: varchar('phone', { length: 32 }),
  village: varchar('village', { length: 128 }),
  block: varchar('block', { length: 128 }),
  district: varchar('district', { length: 128 }),
  registeredFacilityId: varchar('registered_facility_id', { length: 64 }).notNull(),
  registeredDate: varchar('registered_date', { length: 64 }),
  bloodGroup: varchar('blood_group', { length: 16 }),
  emergencyContactName: varchar('emergency_contact_name', { length: 128 }),
  emergencyContactPhone: varchar('emergency_contact_phone', { length: 32 }),
  allergies: jsonb('allergies').$type<string[]>().default([]),
  chronicConditions: jsonb('chronic_conditions').$type<string[]>().default([]),
  currentVitals: jsonb('current_vitals').$type<Record<string, unknown>>(),
  riskCategory: varchar('risk_category', { length: 32 }).notNull().default('Low'),
  highRiskType: varchar('high_risk_type', { length: 64 }),
  ashaWorkerName: varchar('asha_worker_name', { length: 128 }),
  ashaWorkerPhone: varchar('asha_worker_phone', { length: 32 }),
  photoUrl: text('photo_url'),
  lastVisitDate: varchar('last_visit_date', { length: 64 }),
  pastHistorySummary: text('past_history_summary'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const teleconsultations = pgTable('teleconsultations', {
  id: varchar('id', { length: 64 }).primaryKey(),
  tokenNumber: integer('token_number').notNull(),
  patientId: varchar('patient_id', { length: 64 }).notNull(),
  patientName: varchar('patient_name', { length: 255 }).notNull(),
  patientAge: integer('patient_age').notNull(),
  patientGender: varchar('patient_gender', { length: 16 }),
  patientAbhaId: varchar('patient_abha_id', { length: 64 }),
  patientVillage: varchar('patient_village', { length: 128 }),
  requestingFacilityId: varchar('requesting_facility_id', { length: 64 }).notNull(),
  requestingFacilityName: varchar('requesting_facility_name', { length: 255 }).notNull(),
  consultingFacilityId: varchar('consulting_facility_id', { length: 64 }).notNull(),
  consultingFacilityName: varchar('consulting_facility_name', { length: 255 }).notNull(),
  consultingDoctorName: varchar('consulting_doctor_name', { length: 255 }).notNull(),
  specialityRequired: varchar('speciality_required', { length: 128 }).notNull(),
  assistedByAshaName: varchar('assisted_by_asha_name', { length: 128 }),
  chiefComplaints: text('chief_complaints').notNull(),
  symptomsDuration: varchar('symptoms_duration', { length: 64 }),
  vitals: jsonb('vitals').$type<Record<string, unknown>>().notNull(),
  triagePriority: varchar('triage_priority', { length: 32 }).notNull(),
  triageScore: integer('triage_score').default(0),
  triageReason: text('triage_reason'),
  status: varchar('status', { length: 32 }).notNull().default('Waiting'),
  createdAt: varchar('created_at', { length: 64 }).notNull(),
  startedAt: varchar('started_at', { length: 64 }),
  completedAt: varchar('completed_at', { length: 64 }),
  prescription: jsonb('prescription').$type<Record<string, unknown>>(),
  referralId: varchar('referral_id', { length: 64 }),
  meetingRoomId: varchar('meeting_room_id', { length: 128 }).notNull(),
  aiDifferentialDiagnosis: jsonb('ai_differential_diagnosis').$type<string[]>().default([]),
  aiRedFlags: jsonb('ai_red_flags').$type<string[]>().default([]),
  aiRecommendedAction: text('ai_recommended_action'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const referrals = pgTable('referrals', {
  id: varchar('id', { length: 64 }).primaryKey(),
  patientId: varchar('patient_id', { length: 64 }).notNull(),
  patientName: varchar('patient_name', { length: 255 }).notNull(),
  patientAge: integer('patient_age').notNull(),
  patientGender: varchar('patient_gender', { length: 16 }),
  patientAbhaId: varchar('patient_abha_id', { length: 64 }),
  fromFacilityId: varchar('from_facility_id', { length: 64 }).notNull(),
  fromFacilityName: varchar('from_facility_name', { length: 255 }).notNull(),
  toFacilityId: varchar('to_facility_id', { length: 64 }).notNull(),
  toFacilityName: varchar('to_facility_name', { length: 255 }).notNull(),
  speciality: varchar('speciality', { length: 128 }).notNull(),
  reasonForReferral: text('reason_for_referral').notNull(),
  clinicalSummary: text('clinical_summary').notNull(),
  provisionalDiagnosis: text('provisional_diagnosis').notNull(),
  triagePriority: varchar('triage_priority', { length: 32 }).notNull(),
  transportRequirement: varchar('transport_requirement', { length: 64 }).notNull(),
  assignedAmbulanceId: varchar('assigned_ambulance_id', { length: 64 }),
  driverContact: varchar('driver_contact', { length: 32 }),
  teleconsultationId: varchar('teleconsultation_id', { length: 64 }),
  status: varchar('status', { length: 32 }).notNull().default('Initiated'),
  initiatedAt: varchar('initiated_at', { length: 64 }).notNull(),
  acceptedAt: varchar('accepted_at', { length: 64 }),
  inTransitAt: varchar('in_transit_at', { length: 64 }),
  admittedAt: varchar('admitted_at', { length: 64 }),
  completedAt: varchar('completed_at', { length: 64 }),
  acceptingDoctorName: varchar('accepting_doctor_name', { length: 255 }),
  bedAssigned: varchar('bed_assigned', { length: 64 }),
  counterReferralNotes: text('counter_referral_notes'),
  counterReferralMedications: jsonb('counter_referral_medications').$type<Record<string, unknown>[]>(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const labOrders = pgTable('lab_orders', {
  id: varchar('id', { length: 64 }).primaryKey(),
  patientId: varchar('patient_id', { length: 64 }).notNull(),
  patientName: varchar('patient_name', { length: 255 }).notNull(),
  facilityId: varchar('facility_id', { length: 64 }).notNull(),
  testName: varchar('test_name', { length: 255 }).notNull(),
  category: varchar('category', { length: 64 }).notNull(),
  orderedByDoctor: varchar('ordered_by_doctor', { length: 255 }).notNull(),
  orderDate: varchar('order_date', { length: 64 }).notNull(),
  urgency: varchar('urgency', { length: 32 }).notNull(),
  status: varchar('status', { length: 32 }).notNull().default('Pending'),
  resultValue: varchar('result_value', { length: 128 }),
  referenceRange: varchar('reference_range', { length: 128 }),
  isAbnormal: boolean('is_abnormal').default(false),
  notes: text('notes'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const doctors = pgTable('doctors', {
  id: varchar('id', { length: 64 }).primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  qualification: varchar('qualification', { length: 128 }).notNull(),
  registrationNumber: varchar('registration_number', { length: 64 }).notNull(),
  facilityId: varchar('facility_id', { length: 64 }).notNull(),
  facilityName: varchar('facility_name', { length: 255 }).notNull(),
  facilityTier: varchar('facility_tier', { length: 32 }).notNull(),
  speciality: varchar('speciality', { length: 128 }).notNull(),
  subSpeciality: varchar('sub_speciality', { length: 128 }),
  isOnline: boolean('is_online').default(false),
  status: varchar('status', { length: 32 }).notNull().default('Offline'),
  activeQueueCount: integer('active_queue_count').default(0),
  totalConsultsCompleted: integer('total_consults_completed').default(0),
  phone: varchar('phone', { length: 32 }),
  email: varchar('email', { length: 255 }),
  avatarUrl: text('avatar_url'),
  availableDays: jsonb('available_days').$type<string[]>().default([]),
  shiftTiming: varchar('shift_timing', { length: 64 }),
  teleconsultStationId: varchar('teleconsult_station_id', { length: 64 }),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const facilityDatabaseSnapshots = pgTable('facility_database_snapshots', {
  facilityId: varchar('facility_id', { length: 64 }).primaryKey(),
  facilityData: jsonb('facility_data').notNull(),
  lastUpdated: timestamp('last_updated').defaultNow(),
});
